In [10]:
import pandas as pd
import numpy as np

In [11]:


orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104, 105, 106, 107, 108],
    'customer_id': [1, 2, 1, 3, 2, 4, 1, 3],
    'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Laptop', 'Mouse', 'Monitor', 'Laptop'],
    'quantity': [1, 2, 1, 1, 1, 3, 2, 1],
    'price': [1200, 25, 45, 300, 1200, 25, 300, 1250],
    'region': ['West', 'East', 'West', 'South', 'East', 'West', 'South', 'East']
})

customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'name': ['Asha', 'Rahul', 'Priya', 'Vikram'],
    'tier': ['Gold', 'Silver', 'Gold', 'Bronze']
})

In [12]:
print(orders)

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
1       102            2     Mouse         2     25   East
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
4       105            2    Laptop         1   1200   East
5       106            4     Mouse         3     25   West
6       107            1   Monitor         2    300  South
7       108            3    Laptop         1   1250   East

In [13]:
print(customers)

   customer_id    name    tier
0            1    Asha    Gold
1            2   Rahul  Silver
2            3   Priya    Gold
3            4  Vikram  Bronze

In [17]:
orders.tail()

   order_id  customer_id  product  quantity  price region
3       104            3  Monitor         1    300  South
4       105            2   Laptop         1   1200   East
5       106            4    Mouse         3     25   West
6       107            1  Monitor         2    300  South
7       108            3   Laptop         1   1250   East

In [18]:
orders.head()

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
1       102            2     Mouse         2     25   East
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
4       105            2    Laptop         1   1200   East

In [19]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     8 non-null      int64
 1   customer_id  8 non-null      int64
 2   product      8 non-null      str
 3   quantity     8 non-null      int64
 4   price        8 non-null      int64
 5   region       8 non-null      str
dtypes: int64(4), str(2)
memory usage: 516.0 bytes

In [23]:
orders.describe()

        order_id  customer_id  quantity        price
count    8.00000     8.000000  8.000000     8.000000
mean   104.50000     2.125000  1.500000   543.125000
std      2.44949     1.125992  0.755929   568.946002
min    101.00000     1.000000  1.000000    25.000000
25%    102.75000     1.000000  1.000000    40.000000
50%    104.50000     2.000000  1.000000   300.000000
75%    106.25000     3.000000  2.000000  1200.000000
max    108.00000     4.000000  3.000000  1250.000000

In [25]:
orders.shape

(8, 6)

In [28]:
orders.columns

Index(['order_id', 'customer_id', 'product', 'quantity', 'price', 'region'], dtype='str')

In [30]:
orders.dtypes

order_id       int64
customer_id    int64
product          str
quantity       int64
price          int64
region           str
dtype: object

In [33]:
orders.isnull().sum()

order_id       0
customer_id    0
product        0
quantity       0
price          0
region         0
dtype: int64

In [35]:
orders.duplicated().sum()

np.int64(0)

In [37]:
orders.drop_duplicates(inplace=True)

In [39]:
orders.fillna(0,inplace = True)

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
1       102            2     Mouse         2     25   East
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
4       105            2    Laptop         1   1200   East
5       106            4     Mouse         3     25   West
6       107            1   Monitor         2    300  South
7       108            3    Laptop         1   1250   East

Loc application

In [41]:
orders.loc[0]

order_id          101
customer_id         1
product        Laptop
quantity            1
price            1200
region           West
Name: 0, dtype: object

In [43]:
orders.loc[0:6]

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
1       102            2     Mouse         2     25   East
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
4       105            2    Laptop         1   1200   East
5       106            4     Mouse         3     25   West
6       107            1   Monitor         2    300  South

In [45]:
orders.loc[:,["product","price"]]

    product  price
0    Laptop   1200
1     Mouse     25
2  Keyboard     45
3   Monitor    300
4    Laptop   1200
5     Mouse     25
6   Monitor    300
7    Laptop   1250

In [47]:
orders.iloc[0]

order_id          101
customer_id         1
product        Laptop
quantity            1
price            1200
region           West
Name: 0, dtype: object

In [48]:
orders.iloc[0:10]

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
1       102            2     Mouse         2     25   East
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
4       105            2    Laptop         1   1200   East
5       106            4     Mouse         3     25   West
6       107            1   Monitor         2    300  South
7       108            3    Laptop         1   1250   East

In [51]:
orders.iloc[0:5,1:4]

   customer_id   product  quantity
0            1    Laptop         1
1            2     Mouse         2
2            1  Keyboard         1
3            3   Monitor         1
4            2    Laptop         1

exercise 3
boolean filtering

In [53]:
orders[orders["price"]>500]

   order_id  customer_id product  quantity  price region
0       101            1  Laptop         1   1200   West
4       105            2  Laptop         1   1200   East
7       108            3  Laptop         1   1250   East

In [54]:
orders[orders["product"]=="mouse"]

Empty DataFrame
Columns: [order_id, customer_id, product, quantity, price, region]
Index: []

In [55]:
orders[orders["region"]=="West"]

   order_id  customer_id   product  quantity  price region
0       101            1    Laptop         1   1200   West
2       103            1  Keyboard         1     45   West
5       106            4     Mouse         3     25   West

In [58]:
orders[
    (orders["region"]=="West")
    &
    (orders["price"]>500)
]

   order_id  customer_id product  quantity  price region
0       101            1  Laptop         1   1200   West

Exercise 4 

Sort value

In [59]:
orders.sort_values(by="price")

   order_id  customer_id   product  quantity  price region
1       102            2     Mouse         2     25   East
5       106            4     Mouse         3     25   West
2       103            1  Keyboard         1     45   West
3       104            3   Monitor         1    300  South
6       107            1   Monitor         2    300  South
0       101            1    Laptop         1   1200   West
4       105            2    Laptop         1   1200   East
7       108            3    Laptop         1   1250   East

In [60]:
orders.sort_values(by="price",ascending=False)

   order_id  customer_id   product  quantity  price region
7       108            3    Laptop         1   1250   East
0       101            1    Laptop         1   1200   West
4       105            2    Laptop         1   1200   East
3       104            3   Monitor         1    300  South
6       107            1   Monitor         2    300  South
2       103            1  Keyboard         1     45   West
1       102            2     Mouse         2     25   East
5       106            4     Mouse         3     25   West

Exercise5 5

Group by

In [62]:
orders.groupby("region")["price"].mean()

region
East     825.000000
South    300.000000
West     423.333333
Name: price, dtype: float64

In [63]:
orders.groupby("region")["price"].sum()

region
East     2475
South     600
West     1270
Name: price, dtype: int64

Exercise 6

multiple aggregation

In [68]:
orders.groupby("region").agg({
    "price":["sum","mean"]
})

       price
         sum        mean
region
East    2475  825.000000
South    600  300.000000
West    1270  423.333333

merge

In [70]:
merged = orders.merge(customers,on="customer_id")